# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: actnow.canshare.co.nz
canonical: http://canshare.co.nz/fhir
name: actnow
title: ACT-NOW Implementation Guide
description: FHIR support for the New Zealand ACT-NOW standard
status: draft # draft | active | retired | unknown
version: 0.5.0
fhirVersion: 4.0.1 
copyrightYear: 2022+
jurisdiction: urn:iso:std:iso:3166#NZ "New Zealand"
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Te aho o te kahu - Cancer Control Agency
  email: mailto:david.hay25@gmail.com

# use some mcode extensions (laterality)
# use cca extension regimen type
dependencies:
  # hl7.org.nz.fhir.ig.cca: dev

  hl7.fhir.us.mcode:
    id: mcode
    version: 2.0.0

parameters:
  special-url:
    - http://hl7.org.nz/fhir/StructureDefinition/sact-regimen-type
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-toxicity-discontinue-reason
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-who-sact-primary-histology
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-pm
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-pn
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-pt
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-pathological-stage-group
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-patient-factor-discontinue-reason
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-overall-discontinue-reason
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-treatment-intent
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-regimen-outcome
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-cm
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-cn
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-ct
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-her2-expression
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-pr-expression
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-recurrence-type
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-tnm-clinical-stage-group
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-drug-trial
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-dose-adjustment-reason
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-basis-of-cancer-diagnosis
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-ecog-status
    - https://nzhts.digital.health.nz/fhir/ValueSet/canshare-sact-er-expression
    










menu:
  Home: index.html
  Resource graph: resource-graph.html
  Architecture : architecture.html
  API: 
    Input API: api-input.html
    Query API: api-query.html
  Examples: examples.html
  Extensions: extensions.html
  Profiles: profiles.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Reference Implementation: reference-implementation.html
  Support:
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip

