# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: actnow.canshare.co.nz
canonical: http://actnow.canshare.co.nz
name: actnow
title: ACT-NOW Implementation Guide
description: FHIR support for the New Zealand ACT-NOW standard
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 
copyrightYear: 2022+
releaseLabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: Te aho o te kahu - Cancer Control Agency
  # url: http://example.org/example-publisher
  email: mailto:david.hay25@gmail.com

# use some mcode extensions
# dependencies:


   # hl7.fhir.us.mcode:
     # id: mcode
     # version: 2.0.0



menu:
  Home: index.html
  Resource graph: resource-graph.html
  Architecture : architecture.html
  API: 
    Input API: api-input.html
    Query API: api-query.html
  Examples: examples.html
  Extensions: extensions.html
  Profiles: profiles.html
  Terminology: terminology.html
  Artifacts: artifacts.html
  Reference Implementation: reference-implementation.html
  Support:
    Download IG: full-ig.zip
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Artifacts (Json): definitions.json.zip
    Artifacts (Xml): definitions.xml.zip

